version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: delivery-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: delivery_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6.0
    container_name: delivery-mongodb
    restart: always
    ports:
      - "27017:27017"

  auth-service:
    build: ./auth-service
    container_name: delivery-auth
    restart: always
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=chave_secreta_jwt_2026_fallback
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_NAME=delivery_db
      - DB_PASS=postgrespassword
    depends_on:
      - postgres-db

  catalog-service:
    build: ./catalog-service
    container_name: delivery-catalog
    restart: always
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://localhost:27017/catalog_db
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    container_name: delivery-order
    restart: always
    ports:
      - "3003:3003"
    environment:
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_NAME=delivery_db
      - DB_PASS=postgrespassword
    depends_on:
      - postgres-db

  payment-service:
    build: ./payment-service
    container_name: delivery-payment
    restart: always
    ports:
      - "3004:3004"
    environment:
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_NAME=delivery_db
      - DB_PASS=postgrespassword
    depends_on:
      - postgres-db

    frontend-service:
  build: ./frontend-service
  container_name: delivery-frontend
  ports:
    - "80:80"