version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: delivery-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: delivery_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6.0
    container_name: delivery-mongodb
    restart: always
    ports:
      - "27017:27017"